spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/mayunzouyihui/config-repo.git
          username: 309136832@qq.com
          password: xxx
#          basedir: /Users/admin/code/myProjects/java/stick/SpringCloud_Sell/config/basedir
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
management:
  endpoints:
    web:
      expose: "*"